---
title: Das Informatiker-Rezeptbuch
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: page
description: 'This recipe book is written in German because most of the original recipes
  are from german speeking countries.

'
baseurl: ''
url: ''
github_username: red-hedgehogs
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
